# Generated by Django 4.1.5 on 2023-03-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='city',
            field=models.CharField(default='Zamboanga City', editable=False, max_length=255),
        ),
    ]
