# Generated by Django 4.1.5 on 2023-04-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiveadmin', '0003_alter_transaction_expires'),
        ('wholesalers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='reference_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hiveadmin.transaction'),
        ),
    ]
