# Generated by Django 4.1.5 on 2023-02-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wholesalers", "0002_alter_wholesaler_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wholesaler",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wholesaler",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wholesaler",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wholesaler",
            name="contact_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
