# Generated by Django 4.1.5 on 2023-04-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0002_wholesaler_reference_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaler',
            name='reference_num',
        ),
    ]
