# Generated by Django 4.1.5 on 2023-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0002_alter_wholesaler_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='region',
            field=models.CharField(default='Zamboanga Peninsula', editable=False, max_length=255),
        ),
    ]
