# Generated by Django 4.1.5 on 2023-02-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wholesalers", "0002_wholesaler_is_wholesaler"),
    ]

    operations = [
        migrations.AddField(
            model_name="wholesaler",
            name="is_retailer",
            field=models.BooleanField(default=False),
        ),
    ]
