# Generated by Django 4.1.5 on 2023-02-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wholesalers", "0003_wholesaler_is_retailer"),
    ]

    operations = [
        migrations.RemoveField(model_name="wholesaler", name="is_retailer",),
        migrations.RemoveField(model_name="wholesaler", name="is_wholesaler",),
    ]
