# Generated by Django 4.1.5 on 2023-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0005_wholesaler_wholesaler_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
