# Generated by Django 4.1.5 on 2023-04-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0006_wholesaler_expires_wholesaler_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaler',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='transaction',
        ),
    ]
