# Generated by Django 4.1.5 on 2023-02-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0006_wholesaler_city_wholesaler_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
