# Generated by Django 4.1.5 on 2023-04-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiveadmin', '0007_transaction_expires'),
        ('wholesalers', '0007_remove_wholesaler_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiveadmin.transaction'),
        ),
    ]
