# Generated by Django 4.1.5 on 2023-02-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0007_alter_wholesaler_address'),
        ('wholesalers', '0007_alter_wholesaler_color'),
    ]

    operations = [
    ]
