# Generated by Django 4.1.5 on 2023-04-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0008_wholesaler_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
