# Generated by Django 4.1.5 on 2023-03-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0008_merge_20230228_0750'),
        ('wholesalers', '0008_merge_20230228_1551'),
        ('wholesalers', '0008_merge_20230228_1629'),
    ]

    operations = [
    ]
