# Generated by Django 4.1.5 on 2023-04-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0009_wholesaler_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaler',
            name='expires',
        ),
    ]
