# Generated by Django 4.1.5 on 2023-03-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0009_merge_20230301_1247'),
        ('wholesalers', '0009_merge_20230301_1552'),
    ]

    operations = [
    ]
