# Generated by Django 4.1.5 on 2023-03-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0009_merge_20230301_0440'),
        ('wholesalers', '0010_merge_20230301_1925'),
    ]

    operations = [
    ]
