# Generated by Django 4.1.5 on 2023-04-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiveadmin', '0007_transaction_expires'),
        ('wholesalers', '0011_remove_wholesaler_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiveadmin.transaction'),
        ),
    ]
