# Generated by Django 4.1.5 on 2023-03-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0011_merge_20230302_1617'),
        ('wholesalers', '0011_merge_20230302_1911'),
    ]

    operations = [
    ]
