# Generated by Django 4.1.5 on 2023-03-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0012_merge_20230304_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
