# Generated by Django 4.1.5 on 2023-03-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0014_retailerlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetailerLogs',
        ),
    ]
