# Generated by Django 4.1.5 on 2023-02-08 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wholesalers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("is_retailer", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wholesaler",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wholesaler",
                        to="wholesalers.wholesaler",
                    ),
                ),
            ],
        ),
    ]
