# Generated by Django 4.1.5 on 2023-02-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="is_wholesaler",
            field=models.BooleanField(default=False),
        ),
    ]
