# Generated by Django 4.1.5 on 2023-02-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0002_retailer_is_wholesaler"),
    ]

    operations = [
        migrations.RemoveField(model_name="retailer", name="is_retailer",),
        migrations.RemoveField(model_name="retailer", name="is_wholesaler",),
    ]
