# Generated by Django 4.1.5 on 2023-02-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0003_remove_retailer_is_retailer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="retailer_image",
            field=models.ImageField(
                default="products/default.jpg", upload_to="products/"
            ),
        ),
    ]
