# Generated by Django 4.1.5 on 2023-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0008_alter_retailer_retailer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="retailer_image",
            field=models.ImageField(
                blank=True,
                default="products/default.jpg",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
