# Generated by Django 4.1.5 on 2023-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0011_alter_retailer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='retailer',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
