# Generated by Django 4.1.5 on 2023-03-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0010_merge_20230301_1925'),
        ('retailers', '0012_retailer_city_retailer_region_alter_retailer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailer',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='retailer',
            name='wholesaler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailers', to='wholesalers.wholesaler'),
        ),
    ]
