# Generated by Django 4.1.5 on 2023-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0014_retailerlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerlogs',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
