# Generated by Django 4.1.5 on 2023-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiveadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expires',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
