# Generated by Django 4.1.5 on 2023-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiveadmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRetailerLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wholesaler", models.CharField(max_length=255)),
                ("retailer", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminWholesalerLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wholesaler", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
