# Generated by Django 4.1.5 on 2023-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiveadmin', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
