# Generated by Django 4.1.5 on 2023-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiveadmin", "0002_adminretailerlogs_adminwholesalerlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminretailerlogs",
            name="domain",
            field=models.CharField(default="hiluck.localhost", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminwholesalerlogs",
            name="domain",
            field=models.CharField(default="hiluck.localhost", max_length=255),
            preserve_default=False,
        ),
    ]
