# Generated by Django 4.1.5 on 2023-03-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiveadmin', '0003_transaction_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
