# Generated by Django 4.1.5 on 2023-02-21 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart_db", name="size",),
        migrations.AddField(
            model_name="cart_db",
            name="variation",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
