# Generated by Django 4.1.5 on 2023-02-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_rename_actual_stocks_variation_actual_stocks_var_and_more"),
        ("cart", "0003_remove_cart_db_variation_cart_db_variation_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart_db", name="product_id",),
        migrations.RemoveField(model_name="cart_db", name="variation_id",),
        migrations.AddField(
            model_name="cart_db",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cart_db",
            name="variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testest",
                to="products.variation",
            ),
        ),
    ]
