# Generated by Django 4.1.5 on 2023-02-21 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0004_remove_cart_db_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_db",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="okayyy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
