# Generated by Django 4.1.5 on 2023-02-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0005_alter_cart_db_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart_db", name="product",),
        migrations.RemoveField(model_name="cart_db", name="variation",),
        migrations.AddField(
            model_name="cart_db",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="cart_db",
            name="variation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="cart_db",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
