# Generated by Django 4.1.5 on 2023-02-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_rename_actual_stocks_variation_actual_stocks_var_and_more"),
        ("cart", "0011_remove_cart_db_variation_id_cart_db_variations_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart_db", name="variations",),
        migrations.AddField(
            model_name="cart_db",
            name="variation_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="products.variation",
            ),
        ),
        migrations.AlterField(
            model_name="cart_db",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_cart",
                to="products.product",
            ),
        ),
    ]
