# Generated by Django 4.1.5 on 2023-02-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_remove_cart_db_variations_cart_db_variation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart_db", name="subtotal", field=models.FloatField(null=True),
        ),
    ]
