# Generated by Django 4.1.5 on 2023-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="total_paid", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderitem", name="price", field=models.FloatField(),
        ),
    ]
