# Generated by Django 4.1.5 on 2023-02-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_variation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_count", models.IntegerField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
