# Generated by Django 4.1.5 on 2023-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
