# Generated by Django 4.1.5 on 2023-02-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_created"),
    ]

    operations = [
        migrations.DeleteModel(name="Sales",),
    ]
