# Generated by Django 4.1.5 on 2023-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_delete_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="success",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
