# Generated by Django 4.1.5 on 2023-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference_number",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
