# Generated by Django 4.1.5 on 2023-03-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="analytics_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="analytics_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
