# Generated by Django 4.1.5 on 2023-03-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='17289', max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.CharField(default='AE9EF', max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
