# Generated by Django 4.1.5 on 2023-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="with_size",
            field=models.CharField(
                choices=[("True", "Yes"), ("False", "No")],
                default=False,
                max_length=200,
            ),
        ),
    ]
