# Generated by Django 4.1.5 on 2023-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category", name="sold", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventory", name="sold", field=models.IntegerField(default=0),
        ),
    ]
