# Generated by Django 4.1.5 on 2023-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_inventory_with_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="with_size",
            field=models.BooleanField(
                choices=[("True", "Yes"), ("False", "No")], default=False
            ),
        ),
    ]
