# Generated by Django 4.1.5 on 2023-03-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_id_alter_variation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                default="60C57",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="variation",
            name="id",
            field=models.CharField(
                default="F866F",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
