# Generated by Django 4.1.5 on 2023-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(default='medium', max_length=255),
            preserve_default=False,
        ),
    ]
