# Generated by Django 4.1.5 on 2023-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_sold_inventory_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='with_size',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
    ]
