# Generated by Django 4.1.5 on 2023-03-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_analytics_date_variation_analytics_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                default="388EB",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="id",
            field=models.CharField(
                default="20DB2",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
