# Generated by Django 4.1.5 on 2023-03-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_id_alter_product_min_orders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                default="93778",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_orders",
            field=models.IntegerField(
                default=models.IntegerField(blank=True, default=0, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="id",
            field=models.CharField(
                default="89CE1",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
