# Generated by Django 4.1.5 on 2023-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_inventory_size_alter_inventory_with_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
    ]
