# Generated by Django 4.1.5 on 2023-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
