# Generated by Django 4.1.5 on 2023-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_inventory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
