# Generated by Django 4.1.5 on 2023-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_inventory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='with_size',
            field=models.BooleanField(blank=True, choices=[('True', 'Yes'), ('False', 'No')], default=0, null=True),
        ),
    ]
