# Generated by Django 4.1.5 on 2023-02-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_sold_inventory_sold"),
        ("products", "0007_alter_inventory_with_size"),
    ]

    operations = []
