# Generated by Django 4.1.5 on 2023-02-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_inventory_with_size'),
        ('products', '0008_merge_20230219_1927'),
    ]

    operations = [
    ]
