# Generated by Django 4.1.5 on 2023-02-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_merge_20230220_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="with_size",
            field=models.BooleanField(
                blank=True, choices=[(1, "Yes"), (0, "No")], default=0, null=True
            ),
        ),
    ]
