# Generated by Django 4.1.5 on 2023-02-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_merge_20230220_1113"),
        ("products", "0010_alter_inventory_with_size"),
    ]

    operations = []
