# Generated by Django 4.1.5 on 2023-02-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20230220_1547'),
        ('products', '0011_merge_20230220_1552'),
    ]

    operations = [
    ]
