# Generated by Django 4.1.5 on 2023-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0013_alter_inventory_actual_quantity_alter_inventory_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="actual_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="size",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
