# Generated by Django 4.1.5 on 2023-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_inventory_actual_quantity_alter_inventory_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="actual_quantity",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="tempo_quantity",
            field=models.CharField(max_length=200),
        ),
    ]
