# Generated by Django 4.1.5 on 2023-02-20 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_inventory_actual_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="inventory", name="size",),
        migrations.AlterField(
            model_name="inventory",
            name="actual_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="tempo_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.inventory",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Sizes",},
        ),
    ]
