# Generated by Django 4.1.5 on 2023-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_inventory_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="actual_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="tempo_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
