# Generated by Django 4.1.5 on 2023-02-21 03:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wholesalers", "0004_remove_wholesaler_is_retailer_and_more"),
        ("products", "0017_alter_inventory_actual_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="inventory", name="category",),
        migrations.RemoveField(model_name="inventory", name="wholesaler",),
        migrations.RenameField(
            model_name="variation",
            old_name="actual_quantity",
            new_name="actual_stocks",
        ),
        migrations.AddField(
            model_name="variation",
            name="tempo_stocks",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_name", models.CharField(max_length=200)),
                (
                    "actual_stocks",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("tempo_stocks", models.IntegerField(blank=True, default=0, null=True)),
                ("price", models.FloatField()),
                ("with_size", models.BooleanField(choices=[(1, "Yes"), (0, "No")])),
                ("sold", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("min_orders", models.IntegerField(default=0)),
                (
                    "product_image",
                    models.ImageField(
                        default="products/default.jpg", upload_to="products/"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="products.category",
                    ),
                ),
                (
                    "wholesaler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wholesalers.wholesaler",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Inventories",},
        ),
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
