# Generated by Django 4.1.5 on 2023-02-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_remove_inventory_category_and_more"),
        ("orders", "0002_alter_orderitem_product"),
    ]

    operations = [
        migrations.DeleteModel(name="Inventory",),
    ]
