# Generated by Django 4.1.5 on 2023-02-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_delete_inventory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Products"},
        ),
    ]
