# Generated by Django 4.1.5 on 2023-02-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="with_size", new_name="with_variation",
        ),
    ]
