# Generated by Django 4.1.5 on 2023-02-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_rename_with_size_product_with_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="actual_stocks",
            new_name="actual_stocks_var",
        ),
        migrations.RenameField(
            model_name="variation",
            old_name="tempo_stocks",
            new_name="tempo_stocks_var",
        ),
    ]
