# Generated by Django 4.1.5 on 2023-02-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_rename_actual_stocks_variation_actual_stocks_var_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={"ordering": ["created"], "verbose_name_plural": "Sizes"},
        ),
        migrations.AlterField(
            model_name="product",
            name="with_variation",
            field=models.BooleanField(choices=[(1, "Yes"), (0, "No")], default=0),
        ),
    ]
