# Generated by Django 4.1.5 on 2023-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_alter_product_with_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="with_variation",
            field=models.CharField(
                choices=[(1, "Yes"), (0, "No")], max_length=200, null=True
            ),
        ),
    ]
