# Generated by Django 4.1.5 on 2023-03-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0035_alter_product_with_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="min_orders",
            field=models.IntegerField(
                default=models.IntegerField(blank=True, default=0, null=True)
            ),
        ),
    ]
