# Generated by Django 4.1.5 on 2023-03-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0036_alter_product_min_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
